import './style.css';
import {createScene} from './scene.mjs';
import {initialAssembly,assemblyAction,localCommand} from './project.mjs';
import {mountDesignStudio} from './design-ui.mjs';
const $=s=>document.querySelector(s);
const node=(tag,text,className)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(className)n.className=className;return n;};
let config={},project=null,scene=null,state=initialAssembly(),generation=0,poll=null,selectedFiles=[];
function status(text=''){$('#app-status').textContent=text;}
async function api(url,body){const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed.');return d;}
const projectApi=(action,body)=>api(`/api/projects/${project.id}${action?'/'+action:''}`,body);
function run(fn){return async e=>{try{await fn(e);}catch(error){status(error.message);}};}
function cite(target,refs=[]){target.replaceChildren();for(const ref of refs){const page=project.pages.find(p=>p.id===ref.pageId);if(!page)continue;const b=node('button',`${page.name} · ${page.page||1}`);b.type='button';b.addEventListener('click',()=>showSource(page));target.append(b);}}
function showSource(page){$('#source-title').textContent=`${page.name} · page ${page.page||1}`;$('#source-image').src=page.url;$('#source-text').textContent=page.text||'Image source. No extracted text is available.';const original=project.sources.find(s=>s.id===page.sourceId);$('#original-source').href=original?.url||page.url;$('#source-dialog').showModal();}
$('#close-source').addEventListener('click',()=>$('#source-dialog').close());
function clearWorkspace(){generation++;clearTimeout(poll);scene?.dispose();scene=null;$('#workspace-root').replaceChildren();}
async function recent(){const projects=await api('/api/projects');$('#project-list').replaceChildren();for(const p of projects){const b=node('button',p.title||'Untitled upload','project-row');b.append(node('span',p.status));b.addEventListener('click',run(()=>open(p.id)));$('#project-list').append(b);}if(!projects.length)$('#project-list').append(node('p','Your first project starts with an upload.','quiet'));}
async function open(id){clearWorkspace();status();project=await api('/api/projects/'+id);history.replaceState(null,'','#project='+id);$('#landing').hidden=true;$('#project-view').hidden=false;await renderProject();}
async function home(){clearWorkspace();project=null;history.replaceState(null,'',location.pathname);$('#project-view').hidden=true;$('#landing').hidden=false;status();await recent();}
$('#back-home').addEventListener('click',run(home));$('#refresh-projects').addEventListener('click',run(recent));
function pageCards(){const target=$('#source-pages');target.replaceChildren();for(const p of project.pages){const b=node('button',null,'page-card'),img=node('img');img.src=p.url;img.alt=p.name+' page '+p.page;img.loading='lazy';b.append(img,node('span',`${p.name} · page ${p.page}`));b.addEventListener('click',()=>showSource(p));target.append(b);}}
async function renderProject(){
 const p=project,working=['analyzing','building'].includes(p.status);$('#project-title').textContent=p.title||'Your object';$('#project-kind').textContent=p.provenance?.provider||'UPLOADED SOURCES';$('#project-state').textContent=p.status.toUpperCase();$('#project-summary').textContent=p.analysis?.summary||p.manifest?.summary||`${p.sources.length} source files · ${p.pages.length} pages · ready for review`;
 $('#assistant-package').href=`/api/projects/${p.id}/assistant-package`;$('#export-project').href=`/api/projects/${p.id}/export`;
 const message=working?(p.status==='analyzing'?'Reading the source pages. One provider call is in progress…':'Building separate parts and preparing the preview…'):p.error||p.buildWarning||(p.job?.status==='interrupted'&&p.job.message);
 $('#job-status').hidden=!message;$('#job-status').textContent=message||'';
 $('#review-panel').hidden=p.status==='ready'||working;$('#evidence-footer').hidden=p.status!=='ready';$('#analysis-empty').hidden=!!p.analysis;$('#analysis-ready').hidden=!p.analysis;
 pageCards();$('#analysis-availability').textContent=config.analysis?'Vision analysis is available. Review the result before building.':'Live analysis is not configured. Use the assistant package, or add a vision API key in .env and restart.';updateAnalyzeButton();
 if(p.analysis){$('#review-title').value=p.analysis.title;$('#analysis-limitations').textContent=[`${p.analysis.mode.toUpperCase()} · ${p.analysis.scaleBasis} scale`,...p.analysis.limitations].join(' · ');$('#review-parts').replaceChildren();for(const part of p.analysis.parts){const row=node('div',null,'part-review'),label=node('label',part.label),input=node('input');input.value=part.label;input.maxLength=80;input.dataset.part=part.id;label.append(input);row.append(label,node('span',part.evidence,'evidence-tag'),node('small',part.geometryBasis),node('p',part.description));const refs=node('div',null,'citations');cite(refs,part.sources);row.append(refs);$('#review-parts').append(row);}}
 if(working){const id=p.id;poll=setTimeout(run(async()=>{if(project?.id!==id)return;project=await api('/api/projects/'+id);await renderProject();}),1500);return;}
 if(p.status==='ready'&&p.manifest){$('#reopen-review').hidden=!p.analysis;cite($('#source-links'),p.pages.map(x=>({pageId:x.id})));$('#scene-limitations').textContent=p.manifest.limitations.join(' · ');await workspace();}
}
function updateAnalyzeButton(){$('#analyze-project').disabled=!config.analysis||!$('#analysis-consent').checked;}
$('#analysis-consent').addEventListener('change',updateAnalyzeButton);
$('#analyze-project').addEventListener('click',run(async()=>{$('#analyze-project').disabled=true;try{project=await projectApi('analyze',{budgetConfirmed:$('#analysis-consent').checked});await renderProject();}finally{updateAnalyzeButton();}}));
$('#import-scene').addEventListener('click',()=>$('#scene-file').click());
$('#scene-file').addEventListener('change',run(async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>450000)throw Error('Scene JSON must be under 450 KB.');const d=JSON.parse(await file.text());project=await projectApi('import-scene',{scene:d.scene||d});clearWorkspace();await renderProject();status('Scene imported. Check the labels and evidence before building.');}));
$('#build-project').addEventListener('click',run(async()=>{const b=$('#build-project');status();b.disabled=true;try{project=await projectApi('review',{title:$('#review-title').value,parts:[...document.querySelectorAll('#review-parts input')].map(i=>({id:i.dataset.part,label:i.value}))});project=await projectApi('build',{});clearWorkspace();await renderProject();}finally{b.disabled=false;}}));
$('#reopen-review').addEventListener('click',()=>{$('#review-panel').hidden=!$('#review-panel').hidden;});
function execute(command){const result=assemblyAction(state,command,project.manifest);state=result.state;$('#answer').textContent=result.message;$('#answer-label').textContent=state.selected?'PART EVIDENCE':'CONCEPT EXPLORER';cite($('#answer-sources'),result.sources);$('#view-state').textContent=state.flow?'ILLUSTRATED ROUTE':state.mode.toUpperCase();$('#part-label').hidden=!state.selected;if(state.selected)$('#part-label').textContent=project.manifest.parts.find(p=>p.id===state.selected).label;for(const b of document.querySelectorAll('#part-picker button'))b.classList.toggle('active',b.dataset.part===state.selected);for(const b of document.querySelectorAll('[data-action]'))b.classList.toggle('active',b.dataset.action===(state.flow?'flow':state.mode==='exploded'?'explode':'assemble'));scene?.apply(state);}
async function workspace(){
 clearWorkspace();const token=generation,p=project;state=initialAssembly();
 if(p.manifest.mode==='knowledge'){const wrap=node('section',null,'knowledge-panel');wrap.append(node('p','SOURCE KNOWLEDGE / NO GEOMETRY','eyebrow'),node('h2',p.title),node('p','The sources do not support a meaningful 3D reconstruction. Explore the documented information below.'));for(const part of p.manifest.parts){const card=node('div',null,'knowledge-part'),refs=node('div',null,'citations');cite(refs,part.sources);card.append(node('h3',part.label),node('p',part.description),refs);wrap.append(card);}const form=node('form'),label=node('label','Ask these sources'),input=node('input'),button=node('button','Ask with AI ↗','secondary'),answer=node('p'),citations=node('div',null,'citations');input.required=true;input.maxLength=1200;input.placeholder='What does the manual document?';label.className='field';label.append(input);button.disabled=!config.live;form.append(label,button);form.addEventListener('submit',run(async e=>{e.preventDefault();button.disabled=true;try{const result=await projectApi('ask',{text:input.value});if(token!==generation)return;answer.textContent=result.answer;cite(citations,result.pageIds.map(pageId=>({pageId})));}finally{button.disabled=!config.live;}}));wrap.append(form,answer,citations,node('p',config.live?'Questions use your configured API account.':'Live source questions require an API key. The evidence above is available offline.','quiet'));$('#workspace-root').append(wrap);return;}
 $('#workspace-root').append($('#workspace-template').content.cloneNode(true));$('#object-label').textContent=p.title;$('#geometry-label').textContent=`${p.manifest.mode} concept · ${p.manifest.scaleBasis} scale`;$('#assembly-description').textContent=`${p.manifest.parts.length} named parts. Select one to inspect its evidence.`;
 for(const part of p.manifest.parts){const b=node('button',part.label);b.dataset.part=part.id;b.addEventListener('click',()=>execute({action:'focus',part:part.id}));$('#part-picker').append(b);}
 $('[data-action="flow"]').hidden=!p.manifest.process;$('[data-action="explode"]').disabled=p.manifest.mode!=='assembly';
 document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>execute({action:b.dataset.action})));
 $('#home').addEventListener('click',()=>scene?.home(state.mode==='exploded'));$('#live-mode').disabled=!config.live;$('#live-status').textContent=config.live?'Uses your API account':'API optional';
 $('#chat').addEventListener('submit',run(async e=>{e.preventDefault();const send=$('#send'),question=$('#question').value,live=$('#live-mode').checked;send.disabled=true;try{if(live){const result=await projectApi('ask',{text:question});if(token!==generation)return;if(result.part)execute({action:'focus',part:result.part});$('#answer').textContent=result.answer;$('#answer-label').textContent='SOURCE ANSWER';cite($('#answer-sources'),result.pageIds.map(pageId=>({pageId})));}else execute(localCommand(question,p.manifest));}finally{send.disabled=false;}}));
 try{const created=await createScene($('#canvas-host'),p.manifest,id=>execute({action:'focus',part:id}));if(token!==generation){created.dispose();return;}scene=created;$('#loading').hidden=true;mountDesignStudio(scene).configure(config.design);}
 catch(error){if(token!==generation)return;$('#loading').textContent='3D preview unavailable: '+error.message;$('#design-tab').disabled=true;}
}
$('#source-files').addEventListener('change',e=>{selectedFiles=[...e.target.files];const valid=selectedFiles.length>0&&selectedFiles.length<=4&&selectedFiles.every(f=>f.size<=8*1024*1024)&&selectedFiles.reduce((s,f)=>s+f.size,0)<=12*1024*1024;$('#file-list').textContent=selectedFiles.map(f=>`${f.name} (${(f.size/1024/1024).toFixed(1)} MB)`).join(' · ');$('#upload-submit').disabled=!valid;if(!valid&&selectedFiles.length)status('Choose up to 4 files, 8 MB each and 12 MB combined.');else status();});
function base64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});}
$('#upload-form').addEventListener('submit',run(async e=>{e.preventDefault();const b=$('#upload-submit');b.disabled=true;b.textContent='Preparing source pages…';try{const files=await Promise.all(selectedFiles.map(async f=>({name:f.name,data:await base64(f)})));const p=await api('/api/projects',{files});await open(p.id);}finally{b.disabled=false;b.textContent='Create project ↗';}}));
try{config=await api('/api/config');$('#connection-status').textContent=config.analysis?'Vision AI connected':'Local + assisted mode';for(const example of await api('/api/examples')){const b=node('button',null,'example-card'),img=node('img'),copy=node('div');img.src=example.image;img.alt=example.title;copy.append(node('strong',example.title),node('span',example.description));b.append(img,copy);b.addEventListener('click',run(async()=>{b.disabled=true;try{const p=await api('/api/examples/'+example.id,{});await open(p.id);}finally{b.disabled=false;}}));$('#examples').append(b);}const id=location.hash.match(/^#project=([a-f0-9-]{36})$/)?.[1];if(id)await open(id);else await recent();}catch(error){status(error.message);}
